#!/usr/bin/env python3
"""
Turn the collected student advice into assets/data/advice.js.

    python3 tools/advice-to-js.py Advice_from_students_02.txt

assets/data/advice.js is GENERATED. Never hand-edit it: add to the text
file and re-run this, so the file the committee collects stays the one
the site shows.

The text file is one entry per paragraph, an initial then the advice in
double quotes:

    E "Pay attention the most in this semester..."

    R "Ensure you have a deep understanding..."

The initial is shown on the page, after the closing quotation mark,
followed by a comma and YEAR (below) — "E, Year 3". It identifies whose
advice it is without giving a full name.

WORDING IS LEFT ALONE. These are students' own words, typos and all —
correcting them here would put words in their mouths and would be
silently undone the next time this is re-run. Fix the text file if a
wording needs changing.
"""
import os
import re
import sys
import json

# Shown after every initial. Change this if a future cohort's advice is
# collected under a different year — it applies to every entry in this
# file, since the source text carries only an initial, not a year.
YEAR = "Year 3"

HEADER = """\
/* =============================================================
   Connect — advice from students, GENERATED by
   tools/advice-to-js.py. Do not hand-edit.

   Add to the collected text file and re-run

       python3 tools/advice-to-js.py Advice_from_students_02.txt

   The wording is the students' own, transcribed as given.
   ============================================================= */
"""

# an initial (1-3 letters), then the advice in double quotes; the
# initial may be jammed straight against the opening quote, and the
# advice may run over lines
ENTRY = re.compile(r'^\s*([A-Za-z]{1,3})\s*[""](.*?)[""]\s*$', re.S)


def main():
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)

    raw = open(sys.argv[1], encoding="utf-8-sig").read()
    items, skipped = [], []

    for i, block in enumerate(re.split(r"\n\s*\n", raw), start=1):
        if not block.strip():
            continue
        m = ENTRY.match(block.strip())
        if not m:
            skipped.append(block.strip()[:70])
            continue
        text = re.sub(r"\s*\n\s*", " ", m.group(2)).strip()
        if not text:
            continue
        items.append({
            "n": i,
            "by": m.group(1).strip().upper(),
            "year": YEAR,
            "words": len(text.split()),
            "text": text,
        })

    if skipped:
        print("Could not read %d block(s) — they need an initial and quotes:" % len(skipped),
              file=sys.stderr)
        for s in skipped:
            print("   %s..." % s, file=sys.stderr)

    if not items:
        raise SystemExit("Nothing parsed. Check the file's format against the note above.")

    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(here, "assets", "data", "advice.js")
    with open(out, "w", encoding="utf-8") as f:
        f.write(HEADER)
        f.write("window.BIOSOC_ADVICE = ")
        f.write(json.dumps({"items": items}, indent=2, ensure_ascii=False))
        f.write(";\n")

    longest = max(items, key=lambda i: i["words"])
    print("%d pieces of advice -> assets/data/advice.js" % len(items))
    print("  shortest %d words, longest %d words (no. %d), %d on average"
          % (min(i["words"] for i in items), longest["words"], longest["n"],
             round(sum(i["words"] for i in items) / len(items))))
    print("  initials: " + ", ".join(i["by"] for i in items))


if __name__ == "__main__":
    main()
