#!/usr/bin/env python3
"""
Turn the collected student advice into assets/data/advice.js.

    python3 tools/advice-to-js.py Advice_from_students.txt

assets/data/advice.js is GENERATED. Never hand-edit it: add to the text
file and re-run this, so the file the committee collects stays the one
the site shows.

The text file is one entry per paragraph, numbered, with the advice in
double quotes:

    1 "Pay attention the most in this semester..."

    2 "Ensure you have a deep understanding..."

The number is kept only so an entry can be found again in the source;
the site never shows it, and the order on the page is random anyway.

WORDING IS LEFT ALONE. These are students' own words, typos and all —
correcting them here would put words in their mouths and would be
silently undone the next time this is re-run. Fix the text file if a
wording needs changing.
"""
import os
import re
import sys
import json

HEADER = """\
/* =============================================================
   Connect — advice from students, GENERATED by
   tools/advice-to-js.py. Do not hand-edit.

   Add to the collected text file and re-run

       python3 tools/advice-to-js.py Advice_from_students.txt

   The wording is the students' own, transcribed as given.
   ============================================================= */
"""

# a number, then the advice in double quotes; the number may be jammed
# straight against the opening quote, and the advice may run over lines
ENTRY = re.compile(r'^\s*(\d+)\s*[""](.*?)[""]\s*$', re.S)


def main():
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)

    raw = open(sys.argv[1], encoding="utf-8-sig").read()
    items, skipped = [], []

    for block in re.split(r"\n\s*\n", raw):
        if not block.strip():
            continue
        m = ENTRY.match(block.strip())
        if not m:
            skipped.append(block.strip()[:70])
            continue
        text = re.sub(r"\s*\n\s*", " ", m.group(2)).strip()
        if not text:
            continue
        items.append({"n": int(m.group(1)), "words": len(text.split()), "text": text})

    if skipped:
        print("Could not read %d block(s) — they need a number and quotes:" % len(skipped),
              file=sys.stderr)
        for s in skipped:
            print("   %s..." % s, file=sys.stderr)

    if not items:
        raise SystemExit("Nothing parsed. Check the file's format against the note above.")

    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(here, "assets", "data", "advice.js")
    with open(out, "w", encoding="utf-8") as f:
        f.write(HEADER)
        f.write("window.BIOSOC_ADVICE = ")
        f.write(json.dumps({"items": items}, indent=2, ensure_ascii=False))
        f.write(";\n")

    longest = max(items, key=lambda i: i["words"])
    print("%d pieces of advice -> assets/data/advice.js" % len(items))
    print("  shortest %d words, longest %d words (no. %d), %d on average"
          % (min(i["words"] for i in items), longest["words"], longest["n"],
             round(sum(i["words"] for i in items) / len(items))))


if __name__ == "__main__":
    main()
