#!/usr/bin/env python3
"""
Turn a published Outlook calendar (.ics) into assets/data/events.js.

    python3 tools/ics-to-events.py path/to/calendar.ics

assets/data/events.js is GENERATED. Never hand-edit it: change the
calendar in Outlook, save the .ics again, and re-run this. The site then
cannot drift from the calendar.

------------------------------------------------------------------
THE TIMEZONE, AND WHY THIS SCRIPT OVERRIDES IT
------------------------------------------------------------------
The calendar this was built against is written in "W. Europe Standard
Time", which is Microsoft's name for Central European Time. The file
says so itself: its VTIMEZONE declares +0100 standard and +0200
daylight. Leicester is +0000 / +0100.

So an event typed as 18:00 is stored as 16:00 UTC and reaches a student
in Leicester as 17:00 — an hour early, every time.

The wall clock is what the committee meant: "18:00" was typed to mean
six o'clock in Leicester. So REINTERPRET below takes each event's
wall-clock reading and re-reads it in London, which restores the
intended time.

THIS IS A PLASTER, AND IT ONLY COVERS THIS WEBSITE. Students who
subscribe to the Outlook feed get their times from Outlook, not from
here, and will still be an hour out. The real fix is in Outlook:
set the calendar's timezone to "(UTC+00:00) Dublin, Edinburgh, Lisbon,
London", then check every existing event still reads the hour you
meant, because changing the setting moves what the stored times display
as.

Once the source calendar is right, set REINTERPRET = None. The events
then keep whatever timezone the file gives them, which is how it should
be.
"""
import os
import re
import sys
import json
from datetime import datetime, date, timedelta
from zoneinfo import ZoneInfo

REINTERPRET = "Europe/London"   # None once the Outlook calendar is fixed
LOCAL = ZoneInfo("Europe/London")

# The committee tags events in the title. Anything unprefixed is ours.
TAGS = {
    "SU": ("su", "Students’ Union"),
    "School": ("school", "School"),
}
OWN = ("biosoc", "BioSoc")

HEADER = """\
/* =============================================================
   Events — GENERATED by tools/ics-to-events.py. Do not hand-edit.

   Source: the BioSoc calendar published from Outlook. To update,
   save the published .ics again and re-run

       python3 tools/ics-to-events.py calendar.ics

   Times here are the times the committee typed in Outlook, read as
   Leicester time. See the note at the top of the generator before
   changing anything about that.
   ============================================================= */
"""


def unfold(text):
    """RFC 5545 folds long lines by starting the next with a space."""
    return re.sub(r"\r?\n[ \t]", "", text.replace("\r\n", "\n"))


def unescape(value):
    out, i = [], 0
    while i < len(value):
        c = value[i]
        if c == "\\" and i + 1 < len(value):
            nxt = value[i + 1]
            out.append({"n": "\n", "N": "\n", ",": ",", ";": ";", "\\": "\\"}.get(nxt, nxt))
            i += 2
            continue
        out.append(c)
        i += 1
    return "".join(out)


def parse_line(line):
    """SUMMARY;LANGUAGE=en-GB:Thing -> ("SUMMARY", {"LANGUAGE": "en-GB"}, "Thing")"""
    head, _, value = line.partition(":")
    parts = head.split(";")
    name = parts[0].upper()
    params = {}
    for p in parts[1:]:
        k, _, v = p.partition("=")
        params[k.upper()] = v.strip('"')
    return name, params, value


def to_local(value, params, zones):
    """One DTSTART/DTEND as an aware datetime in Leicester, plus all-day."""
    if params.get("VALUE") == "DATE" or re.fullmatch(r"\d{8}", value):
        d = datetime.strptime(value, "%Y%m%d").date()
        return datetime(d.year, d.month, d.day, tzinfo=LOCAL), True

    if value.endswith("Z"):
        naive = datetime.strptime(value, "%Y%m%dT%H%M%SZ")
        return naive.replace(tzinfo=ZoneInfo("UTC")).astimezone(LOCAL), False

    naive = datetime.strptime(value, "%Y%m%dT%H%M%S")
    if REINTERPRET:
        # the wall clock is what was meant; read it here instead
        return naive.replace(tzinfo=ZoneInfo(REINTERPRET)).astimezone(LOCAL), False

    tz = zones.get(params.get("TZID", ""))
    if tz is None:
        raise SystemExit(
            "Unknown TZID %r and no VTIMEZONE for it. Either add a mapping or "
            "set REINTERPRET." % params.get("TZID")
        )
    return naive.replace(tzinfo=tz).astimezone(LOCAL), False


def timezones(text):
    """
    Map each VTIMEZONE's TZID onto a real zone, by its offsets rather than
    its name: Microsoft's names are Windows names, not IANA ones, and
    "W. Europe Standard Time" is not a zone any tz database has heard of.
    """
    found = {}
    for block in re.findall(r"BEGIN:VTIMEZONE\n(.*?)END:VTIMEZONE", text, re.S):
        tzid = re.search(r"^TZID:(.*)$", block, re.M)
        std = re.search(r"BEGIN:STANDARD\n.*?TZOFFSETTO:([+-]\d{4})", block, re.S)
        if not (tzid and std):
            continue
        offset = std.group(1)
        found[tzid.group(1).strip()] = {
            "+0000": ZoneInfo("Europe/London"),
            "+0100": ZoneInfo("Europe/Berlin"),
        }.get(offset)
    return found


def split_tag(summary):
    m = re.match(r"^\s*\[([^\]]+)\]\s*(.*)$", summary)
    if not m:
        return OWN[0], OWN[1], summary.strip()
    slug, label = TAGS.get(m.group(1).strip(), (m.group(1).strip().lower(), m.group(1).strip()))
    return slug, label, m.group(2).strip()


def events(text, zones):
    out = []
    for block in re.findall(r"BEGIN:VEVENT\n(.*?)END:VEVENT", text, re.S):
        fields, start, end, all_day = {}, None, None, False
        for line in block.split("\n"):
            if not line.strip():
                continue
            name, params, value = parse_line(line)
            if name == "DTSTART":
                start, all_day = to_local(value, params, zones)
            elif name == "DTEND":
                end, _ = to_local(value, params, zones)
            elif name in ("SUMMARY", "LOCATION", "DESCRIPTION", "UID", "STATUS", "URL"):
                fields[name] = unescape(value)

        if not start or fields.get("STATUS") == "CANCELLED":
            continue
        if end is None:
            end = start + (timedelta(days=1) if all_day else timedelta(hours=1))

        slug, label, title = split_tag(fields.get("SUMMARY", "Untitled"))
        note = fields.get("DESCRIPTION", "").strip()
        out.append({
            "uid": fields.get("UID", ""),
            "title": title,
            "tag": slug,
            "tagLabel": label,
            "start": start.isoformat(),
            "end": end.isoformat(),
            "allDay": all_day,
            "where": fields.get("LOCATION", "").strip(),
            "note": note,
            "url": fields.get("URL", "").strip(),
        })
    out.sort(key=lambda e: e["start"])
    return out


def main():
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    raw = unfold(open(sys.argv[1], encoding="utf-8-sig").read())
    zones = timezones(raw)
    found = events(raw, zones)

    name = re.search(r"^X-WR-CALNAME:(.*)$", raw, re.M)
    payload = {
        "name": (name.group(1).strip() if name else "BioSoc"),
        "builtFrom": os.path.basename(sys.argv[1]),
        "builtAt": datetime.now(LOCAL).replace(microsecond=0).isoformat(),
        "reinterpreted": REINTERPRET,
        "events": found,
    }

    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(here, "assets", "data", "events.js")
    with open(out, "w", encoding="utf-8") as f:
        f.write(HEADER)
        f.write("window.BIOSOC_EVENTS = ")
        f.write(json.dumps(payload, indent=2, ensure_ascii=False))
        f.write(";\n")

    print("%d events -> %s" % (len(found), os.path.relpath(out, here)))
    for e in found:
        print("  %s  %-28s %s" % (e["start"][:16].replace("T", " "), e["title"][:28], e["tagLabel"]))
    if REINTERPRET:
        print("\nNOTE: wall-clock times re-read in %s. The Outlook feed itself is "
              "still in the calendar's own timezone." % REINTERPRET)


if __name__ == "__main__":
    main()
